spring.datasource:
  url: jdbc:postgresql://localhost:5432/la_telegram
  username: lauser
  password: lauser!

spring.rabbitmq:
  host: localhost
  username: rabbit
  password: rabbit

#spring.jpa.hibernate.ddl-auto: create

org.lizaalert:
  checkDelay: ${CHECK_DELAY}
  app.token: ${APP_TOKEN}
  botan.token: ${BOTAN_TOKEN}
  telegram.token: ${TELEGRAM_TOKEN}
  telegram.url: https://api.telegram.org/bot%s/%s
  viewforum.url: http://lizaalert.org/forum/viewforum.php?f=%d
  viewtopic.url: http://lizaalert.org/forum/viewtopic.php?t=%d&view=print

liquibase:
  change-log: classpath:liquibase/changelog.yml

logging.level:
  org.lizaalert: DEBUG